site_name: test mkdocs site new name
site_url: https://github.com/jay-m-dev/test-mkdocs

repo_url: https://github.com/jay-m-dev/test-mkdocs
edit_uri: edit/master/docs_sources/
docs_dir: docs_sources/
site_dir: docs/
theme: readthedocs

nav:
  - Home: index.md
